#!/usr/bin/env python3
import sys
import os
import re
import shutil
import subprocess
import glob

# Constants
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ENV_FILE = os.path.join(BASE_DIR, '.env')

ETC_DIR = os.path.join(BASE_DIR, 'etc')
LE_CONFIG_FILE = os.path.join(ETC_DIR, 'traefik', 'enabled', 'letsencrypt.yml')
MKCERT_CONFIG_FILE = os.path.join(ETC_DIR, 'traefik', 'enabled', 'mkcert.yml')

MKCERT_DIR = os.path.join(ETC_DIR, 'mkcert')
CAROOT_DIR = os.path.join(MKCERT_DIR, 'rootCA')

# RFC 1035 / RFC 1123 compliant domain name validation regex
DOMAIN_REGEX = re.compile(
    r'^([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])'
    r'(\.([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9]))*$'
)

# ----------------------------------------------------------------------
# Helper Functions
# ----------------------------------------------------------------------
def validate_domain(domain):
    if not DOMAIN_REGEX.match(domain) or len(domain) > 253:
        print(f"Error: Invalid domain name '{domain}'")
        sys.exit(1)

def normalize_domains(domains):
    normalized = []
    for d in domains:
        clean = d.strip()
        if clean.startswith('*.'):
            clean = clean[2:]
        elif clean.startswith('*'):
            clean = clean[1:]
        normalized.append(clean)
    
    # Deduplicate while preserving order
    seen = set()
    deduped = []
    for n in normalized:
        if n not in seen:
            seen.add(n)
            deduped.append(n)
    return deduped

# ----------------------------------------------------------------------
# Let's Encrypt Certificates Logic
# ----------------------------------------------------------------------
def read_env_le_domains():
    if not os.path.exists(ENV_FILE):
        return []
    with open(ENV_FILE, 'r') as f:
        for line in f:
            line = line.strip()
            if line.startswith('LETSENCRYPT_DOMAINS='):
                val = line.split('=', 1)[1].strip()
                if (val.startswith('"') and val.endswith('"')) or (val.startswith("'") and val.endswith("'")):
                    val = val[1:-1]
                if not val:
                    return []
                return [d.strip() for d in val.split(',') if d.strip()]
    return []

def write_env_le_domains(domains):
    lines = []
    found = False
    val = ",".join(domains)
    if os.path.exists(ENV_FILE):
        with open(ENV_FILE, 'r') as f:
            lines = f.readlines()
    
    new_line = f'LETSENCRYPT_DOMAINS="{val}"\n'
    
    for i, line in enumerate(lines):
        if line.strip().startswith('LETSENCRYPT_DOMAINS='):
            lines[i] = new_line
            found = True
            break
            
    if not found:
        if lines and not lines[-1].endswith('\n'):
            lines[-1] = lines[-1] + '\n'
        lines.append(new_line)
        
    with open(ENV_FILE, 'w') as f:
        f.writelines(lines)

def ensure_acme_storage():
    """Ensures acme.json exists with 0600 permissions."""
    le_dir = os.path.join(ETC_DIR, 'letsencrypt')
    acme_file = os.path.join(le_dir, 'acme.json')
    os.makedirs(le_dir, exist_ok=True)
    if not os.path.exists(acme_file):
        with open(acme_file, 'w') as f:
            f.write('')
        os.chmod(acme_file, 0o600)
        print(f"Created Let's Encrypt storage file at {acme_file} with 0600 permissions.")

def generate_le_yaml(domains):
    ensure_acme_storage()
    if not domains:
        content = "# No Let's Encrypt domains configured.\n"
        with open(LE_CONFIG_FILE, 'w') as f:
            f.write(content)
        print(f"Cleared Let's Encrypt configuration at {LE_CONFIG_FILE}")
        return

    yaml_lines = [
        "# This file is auto-generated by certificates.py. Do not edit manually.",
        "http:",
        "  routers:"
    ]

    for domain in domains:
        safe_name = domain.replace('.', '-').replace('_', '-')
        yaml_lines.extend([
            f"    letsencrypt-{safe_name}:",
            f"      entryPoints:",
            f"        - websecure",
            f"      rule: Host(`letsencrypt-trigger.{domain}`)",
            f"      service: api@internal",
            f"      tls:",
            f"        certResolver: letsencrypt",
            f"        domains:",
            f"          - main: {domain}",
            f"            sans:",
            f"              - \"*.{domain}\""
        ])

    with open(LE_CONFIG_FILE, 'w') as f:
        f.write("\n".join(yaml_lines) + "\n")
    print(f"Generated Let's Encrypt configuration at {LE_CONFIG_FILE} for domains: {', '.join(domains)}")

# ----------------------------------------------------------------------
# Local Mkcert Certificates Logic
# ----------------------------------------------------------------------
def scan_local_certs():
    """Scans the MKCERT_DIR for valid .pem + -key.pem pairs."""
    certs = []
    if not os.path.exists(MKCERT_DIR):
        return certs
        
    pem_files = glob.glob(os.path.join(MKCERT_DIR, '*.pem'))
    for pem_path in pem_files:
        filename = os.path.basename(pem_path)
        if filename in ('rootCA.pem', 'rootCA-key.pem'):
            continue
            
        base_name = filename[:-4] # strip '.pem'
        key_filename = f"{base_name}-key.pem"
        key_path = os.path.join(MKCERT_DIR, key_filename)
        
        if os.path.exists(key_path):
            certs.append({
                'certFile': f"/etc/mkcert/{filename}",
                'keyFile': f"/etc/mkcert/{key_filename}",
                'name': base_name
            })
            
    # Sort certificates for stable generation order
    certs.sort(key=lambda x: x['name'])
    return certs

def generate_default_self_signed():
    """Generates a generic, anonymous self-signed certificate using OpenSSL to prevent SNI/traefik/mkcert leaks."""
    os.makedirs(MKCERT_DIR, exist_ok=True)
    cert_file = os.path.join(MKCERT_DIR, 'default.pem')
    key_file = os.path.join(MKCERT_DIR, 'default-key.pem')
    
    if not os.path.exists(cert_file) or not os.path.exists(key_file):
        print("Generating generic fallback self-signed certificate...")
        try:
            subprocess.run([
                'openssl', 'req', '-x509', '-newkey', 'rsa:2048', '-nodes',
                '-keyout', key_file,
                '-out', cert_file,
                '-days', '3650',
                '-subj', '/CN=localhost',
                '-sha256',
                '-addext', 'subjectAltName=DNS:localhost,IP:127.0.0.1,IP:::1'
            ], check=True)
            print("Generic fallback self-signed certificate generated.")
        except subprocess.CalledProcessError as e:
            print(f"Warning: Failed to generate generic self-signed certificate: {e}")

def generate_mkcert_yaml():
    # Ensure generic fallback certificate always exists
    generate_default_self_signed()

    certs = scan_local_certs()
    if not certs:
        content = "# No local certificates found.\ntls:\n  certificates: []\n"
        with open(MKCERT_CONFIG_FILE, 'w') as f:
            f.write(content)
        print(f"Cleared local certificates configuration at {MKCERT_CONFIG_FILE}")
        return

    # Determine default certificate: prioritize the generic 'default' cert to prevent leaking domains
    default_cert = None
    for c in certs:
        if c['name'] == 'default':
            default_cert = c
            break

    yaml_lines = [
        "# This file is auto-generated by certificates.py. Do not edit manually.",
        "tls:",
        "  certificates:"
    ]

    for c in certs:
        yaml_lines.extend([
            f"    - certFile: {c['certFile']}",
            f"      keyFile: {c['keyFile']}"
        ])

    if default_cert:
        yaml_lines.extend([
            "  stores:",
            "    default:",
            "      defaultCertificate:",
            f"        certFile: {default_cert['certFile']}",
            f"        keyFile: {default_cert['keyFile']}"
        ])

    with open(MKCERT_CONFIG_FILE, 'w') as f:
        f.write("\n".join(yaml_lines) + "\n")
    print(f"Generated local certificates configuration at {MKCERT_CONFIG_FILE} with {len(certs)} certs.")

def ensure_mkcert_installed():
    """Runs mkcert -install if Root CA does not exist."""
    if not shutil.which('mkcert'):
        print("Error: 'mkcert' command not found in PATH. Please install it first.")
        sys.exit(1)
        
    root_ca_file = os.path.join(CAROOT_DIR, 'rootCA.pem')
    if not os.path.exists(root_ca_file):
        print("Root CA not found. Installing mkcert CA...")
        # Create directory structure if needed
        os.makedirs(CAROOT_DIR, exist_ok=True)
        # Run mkcert -install with custom CAROOT env
        env = {**os.environ, 'CAROOT': CAROOT_DIR}
        try:
            subprocess.run(['mkcert', '-install'], env=env, check=True)
        except subprocess.CalledProcessError as e:
            print(f"Error: Failed to install mkcert CA: {e}")
            sys.exit(1)

def add_mkcert(domains):
    ensure_mkcert_installed()
    env = {**os.environ, 'CAROOT': CAROOT_DIR}
    
    for domain in domains:
        validate_domain(domain)
        print(f"Generating certificates for {domain} and *.{domain}...")
        try:
            # Generate the certificate inside the MKCERT_DIR folder
            subprocess.run(
                ['mkcert', domain, f"*.{domain}"],
                cwd=MKCERT_DIR,
                env=env,
                check=True
            )
        except subprocess.CalledProcessError as e:
            print(f"Error: Failed to generate certificate for {domain}: {e}")
            sys.exit(1)
            
    # Regenerate config index
    generate_mkcert_yaml()

def remove_mkcert(domains):
    for domain in domains:
        validate_domain(domain)
        # mkcert names files by SAN count: domain.pem, domain+1.pem, domain+2.pem,
        # ... (with matching -key.pem). Glob every SAN-count variant so multi-SAN
        # certs do not leak files on removal.
        matches = glob.glob(os.path.join(MKCERT_DIR, f"{domain}.pem")) \
            + glob.glob(os.path.join(MKCERT_DIR, f"{domain}-key.pem")) \
            + glob.glob(os.path.join(MKCERT_DIR, f"{domain}+[0-9]*.pem")) \
            + glob.glob(os.path.join(MKCERT_DIR, f"{domain}+[0-9]*-key.pem"))

        removed = False
        for p in sorted(set(matches)):
            os.remove(p)
            print(f"Deleted local file: {p}")
            removed = True

        if not removed:
            print(f"Warning: No local cert files found for domain '{domain}'")

    # Regenerate config index
    generate_mkcert_yaml()

def list_mkcerts():
    certs = scan_local_certs()
    if not certs:
        print("No local mkcert certificates found.")
        return
        
    print(f"{'Domain / Naming':<30} {'Cert File':<40} {'Key File':<40}")
    print("-" * 115)
    for c in certs:
        # Extract clean domain name by stripping +1 or other indicators
        name = c['name']
        if name.endswith('+1'):
            name = name[:-2]
        print(f"{name:<30} {os.path.basename(c['certFile']):<40} {os.path.basename(c['keyFile']):<40}")

# ----------------------------------------------------------------------
# Main Execution
# ----------------------------------------------------------------------
USAGE = """Usage: certificates.py <resource> <action> [domains...]

Resources and actions:
  le add <domains...>       Add Let's Encrypt domains and regenerate config
  le remove <domains...>    Remove Let's Encrypt domains and regenerate config
  le list                   List configured Let's Encrypt domains
  le gen                    Regenerate the Let's Encrypt dynamic config

  mkcert add <domains...>   Issue local mkcert certificates (domain + *.domain)
  mkcert remove <domains...> Delete local mkcert certificates
  mkcert list               List local mkcert certificates
  mkcert gen                Regenerate the local certificates dynamic config
"""


def require_domains(args):
    if not args:
        print("Error: No domains provided.")
        sys.exit(1)
    return normalize_domains(args)


def le_add(args):
    new_domains = require_domains(args)
    for d in new_domains:
        validate_domain(d)
    current = read_env_le_domains()
    updated = list(current)
    added = []
    for d in new_domains:
        if d not in updated:
            updated.append(d)
            added.append(d)
    if added:
        write_env_le_domains(updated)
        generate_le_yaml(updated)
        print(f"Added domains: {', '.join(added)}")
    else:
        print("All domains already present in configuration.")


def le_remove(args):
    to_remove = require_domains(args)
    current = read_env_le_domains()
    updated = [d for d in current if d not in to_remove]
    removed = [d for d in to_remove if d in current]
    if removed:
        write_env_le_domains(updated)
        generate_le_yaml(updated)
        print(f"Removed domains: {', '.join(removed)}")
    else:
        print("None of the specified domains were found in configuration.")


def le_list(_args):
    domains = read_env_le_domains()
    if not domains:
        print("No Let's Encrypt domains configured.")
    else:
        for d in domains:
            print(d)


def le_gen(_args):
    generate_le_yaml(read_env_le_domains())


def mkcert_add(args):
    add_mkcert(require_domains(args))


def mkcert_remove(args):
    remove_mkcert(require_domains(args))


def mkcert_list(_args):
    list_mkcerts()


def mkcert_gen(_args):
    generate_mkcert_yaml()


# resource -> action -> handler
COMMANDS = {
    'le': {
        'add': le_add,
        'remove': le_remove,
        'list': le_list,
        'gen': le_gen,
    },
    'mkcert': {
        'add': mkcert_add,
        'remove': mkcert_remove,
        'list': mkcert_list,
        'gen': mkcert_gen,
    },
}


def main():
    args = sys.argv[1:]
    if not args or args[0] in ('-h', '--help', 'help'):
        print(USAGE)
        sys.exit(0 if args else 1)

    resource = args[0]
    if resource not in COMMANDS:
        print(f"Unknown resource: {resource}\n")
        print(USAGE)
        sys.exit(1)

    if len(args) < 2 or args[1] not in COMMANDS[resource]:
        action = args[1] if len(args) >= 2 else "(none)"
        print(f"Unknown action for '{resource}': {action}\n")
        print(USAGE)
        sys.exit(1)

    COMMANDS[resource][args[1]](args[2:])


if __name__ == '__main__':
    main()
